services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sensors
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./timescaledb_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  ingest_api:
    build:
      context: .
      dockerfile: ./ingest/Dockerfile
    container_name: ingest_api
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - timescaledb
    environment:
      - REDIS_HOST=redis
      - DB_HOST=timescaledb
      - DB_NAME=sensors
      - DB_USER=postgres
      - DB_PASS=postgres
    restart: always

  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    container_name: worker
    depends_on:
      - redis
      - timescaledb
    environment:
      - REDIS_HOST=redis
      - DB_HOST=timescaledb
      - DB_NAME=sensors
      - DB_USER=postgres
      - DB_PASS=postgres
    restart: always

  query:
    build:
      context: .
      dockerfile: ./query/Dockerfile
    container_name: query
    environment:
      - DB_HOST=timescaledb
      - DB_NAME=sensors
      - DB_USER=postgres
      - DB_PASS=postgres
    ports:
      - "8001:8001"
    depends_on:
      - timescaledb
    restart: always

volumes:
  timescale_data: